/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as CalculatorsSwpRouteImport } from './routes/calculators.swp'
import { Route as CalculatorsGoldReturnsRouteImport } from './routes/calculators.gold-returns'
import { Route as CalculatorsDebtEngineRouteImport } from './routes/calculators.debt-engine'
import { Route as CalculatorsChildLegacyRouteImport } from './routes/calculators.child-legacy'
import { Route as CalculatorsAssetAllocationRouteImport } from './routes/calculators.asset-allocation'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSwpRoute = CalculatorsSwpRouteImport.update({
  id: '/calculators/swp',
  path: '/calculators/swp',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsGoldReturnsRoute = CalculatorsGoldReturnsRouteImport.update({
  id: '/calculators/gold-returns',
  path: '/calculators/gold-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsDebtEngineRoute = CalculatorsDebtEngineRouteImport.update({
  id: '/calculators/debt-engine',
  path: '/calculators/debt-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsChildLegacyRoute = CalculatorsChildLegacyRouteImport.update({
  id: '/calculators/child-legacy',
  path: '/calculators/child-legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsAssetAllocationRoute =
  CalculatorsAssetAllocationRouteImport.update({
    id: '/calculators/asset-allocation',
    path: '/calculators/asset-allocation',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/asset-allocation': typeof CalculatorsAssetAllocationRoute
  '/calculators/child-legacy': typeof CalculatorsChildLegacyRoute
  '/calculators/debt-engine': typeof CalculatorsDebtEngineRoute
  '/calculators/gold-returns': typeof CalculatorsGoldReturnsRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/asset-allocation': typeof CalculatorsAssetAllocationRoute
  '/calculators/child-legacy': typeof CalculatorsChildLegacyRoute
  '/calculators/debt-engine': typeof CalculatorsDebtEngineRoute
  '/calculators/gold-returns': typeof CalculatorsGoldReturnsRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/calculators': typeof CalculatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/asset-allocation': typeof CalculatorsAssetAllocationRoute
  '/calculators/child-legacy': typeof CalculatorsChildLegacyRoute
  '/calculators/debt-engine': typeof CalculatorsDebtEngineRoute
  '/calculators/gold-returns': typeof CalculatorsGoldReturnsRoute
  '/calculators/swp': typeof CalculatorsSwpRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/report'
    | '/sitemap.xml'
    | '/calculators/asset-allocation'
    | '/calculators/child-legacy'
    | '/calculators/debt-engine'
    | '/calculators/gold-returns'
    | '/calculators/swp'
    | '/legal/$slug'
    | '/calculators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/report'
    | '/sitemap.xml'
    | '/calculators/asset-allocation'
    | '/calculators/child-legacy'
    | '/calculators/debt-engine'
    | '/calculators/gold-returns'
    | '/calculators/swp'
    | '/legal/$slug'
    | '/calculators'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/report'
    | '/sitemap.xml'
    | '/calculators/asset-allocation'
    | '/calculators/child-legacy'
    | '/calculators/debt-engine'
    | '/calculators/gold-returns'
    | '/calculators/swp'
    | '/legal/$slug'
    | '/calculators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CalculatorsAssetAllocationRoute: typeof CalculatorsAssetAllocationRoute
  CalculatorsChildLegacyRoute: typeof CalculatorsChildLegacyRoute
  CalculatorsDebtEngineRoute: typeof CalculatorsDebtEngineRoute
  CalculatorsGoldReturnsRoute: typeof CalculatorsGoldReturnsRoute
  CalculatorsSwpRoute: typeof CalculatorsSwpRoute
  LegalSlugRoute: typeof LegalSlugRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/swp': {
      id: '/calculators/swp'
      path: '/calculators/swp'
      fullPath: '/calculators/swp'
      preLoaderRoute: typeof CalculatorsSwpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/gold-returns': {
      id: '/calculators/gold-returns'
      path: '/calculators/gold-returns'
      fullPath: '/calculators/gold-returns'
      preLoaderRoute: typeof CalculatorsGoldReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/debt-engine': {
      id: '/calculators/debt-engine'
      path: '/calculators/debt-engine'
      fullPath: '/calculators/debt-engine'
      preLoaderRoute: typeof CalculatorsDebtEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/child-legacy': {
      id: '/calculators/child-legacy'
      path: '/calculators/child-legacy'
      fullPath: '/calculators/child-legacy'
      preLoaderRoute: typeof CalculatorsChildLegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/asset-allocation': {
      id: '/calculators/asset-allocation'
      path: '/calculators/asset-allocation'
      fullPath: '/calculators/asset-allocation'
      preLoaderRoute: typeof CalculatorsAssetAllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CalculatorsAssetAllocationRoute: CalculatorsAssetAllocationRoute,
  CalculatorsChildLegacyRoute: CalculatorsChildLegacyRoute,
  CalculatorsDebtEngineRoute: CalculatorsDebtEngineRoute,
  CalculatorsGoldReturnsRoute: CalculatorsGoldReturnsRoute,
  CalculatorsSwpRoute: CalculatorsSwpRoute,
  LegalSlugRoute: LegalSlugRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
